spring:
  redis:
    host: 192.168.64.100
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  data:
    mongodb:
      host: 192.168.64.100
      port: 27017
      database: notice
#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG