server:
  port: 8003
  servlet:
    context-path: /storage
spring:
  application:
    name: hitch-storage-server
    ######################### 数据源连接池的配置信息  #################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.100:3306/hitch?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    initialSize: 10
    minIdle: 20
    maxActive: 100
    maxWait: 60000
  #### nacos 配置#######
  cloud:
    nacos:
      server-addr: 192.168.64.100:8848

#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
#      time-to-live: 600000ms
#      use-key-prefix: true

  redis:
    host: 192.168.64.100
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  rabbitmq:
    host: 192.168.64.100
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#minio的完整url会写入后台的数据库
#例如：http://192.168.64.100:9005/prize/1701754725603.jpeg
#所以要保障其可访问性，尤其是docker部署的时候，应该是宿主机暴露的端口！
minio:
  url: http://192.168.64.100:9005
  host: 192.168.64.100
  port: 9005
  bucket: hitch
  username: minioadmin
  password: minioadmin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.heima.modules.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl